"""Assemble the sections' results into the report, the public summary and the issue body.

Owner: builder B1 (R1 At a glance + Verdicts, R2 issue-body sizing, R3 timing in headings, R7 a
section that could not be read says so, R72 the privacy pass over everything).
"""
import time
from urllib.parse import quote

from panel.ops.debug_report._base import LEVELS

# A GitHub new-issue URL is a GET; past about 8 KB of URL, GitHub refuses it. The body is encoded
# into the query string, so this is a budget on the ENCODED body.
ISSUE_BODY_MAX_ENCODED = 7000
ISSUE_PROMPT = ("**Describe the problem here** (what you did, what you expected, what happened). "
                "For the full report, attach the downloaded debug file.\n\n---\n")
_ORDER = {lvl: i for i, lvl in enumerate(LEVELS)}


def _heading(title, status, seconds, detail):
    if status == "ok":
        return "### %s _(read in %.2f s)_" % (title, seconds)
    if status == "timeout":
        return "### %s _(timed out after %.0f s; not shown)_" % (title, seconds)
    return "### %s _(could not be read: %s)_" % (title, detail)


def _glance(sections, results):
    """At a glance: every non-ok finding, fail first, then each section that could not be read."""
    items = []
    for key, title, _module, _mode, _part in sections:
        status, _sec, res = results[key]
        if status != "ok":
            items.append(("unread", title, "could not be read" if status == "error"
                          else "timed out"))
            continue
        for f in res.findings:
            if f["level"] != "ok":
                items.append((f["level"], f["area"], f["text"]))
    items.sort(key=lambda it: _ORDER.get(it[0], 9))
    return ["- [%s] %s: %s" % it for it in items]


def _size_issue_body(summary):
    """The prompt first, then whole summary lines until the encoded body would pass the budget."""
    out = ISSUE_PROMPT
    budget = ISSUE_BODY_MAX_ENCODED
    used = len(quote(out, safe=""))
    note = "\n_(cut to fit a GitHub link; the full report is in the download)_\n"
    note_len = len(quote(note, safe=""))
    lines = summary.split("\n")
    for line in lines:
        piece = line + "\n"
        cost = len(quote(piece, safe=""))
        if used + cost + note_len > budget:
            return out + note
        out += piece
        used += cost
    return out


def assemble(ctx, results):
    """{report, summary, issue_body, issues_url, filename} from {key: (status, s, Result|cls)}."""
    from panel.ops import system_ops as so
    from panel.ops.debug_report import SECTIONS, header, privacy

    try:
        head = header.header_lines(ctx)
    except Exception as exc:  # noqa: BLE001 - a header that cannot be built still gets a report
        head = ["- **Generated**: %s" % time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "- **Header**: could not be read (%s)" % type(exc).__name__]
    took = time.monotonic() - ctx.started
    head.append("- **Report built in**: %.2f s" % took)

    glance = _glance(SECTIONS, results)
    verdicts = []
    for key, _title, _module, _mode, _part in SECTIONS:
        status, _sec, res = results[key]
        if status == "ok" and res.verdict:
            verdicts.append("- " + res.verdict)

    summary_parts = ["## LinuxGSM Panel debug report", ""] + head + [""]
    summary_parts += ["### At a glance"] + (glance or ["- no problems found"]) + [""]
    if verdicts:
        summary_parts += ["### Verdicts"] + verdicts + [""]
    full_parts = []
    for key, title, _module, _mode, part in SECTIONS:
        status, sec, res = results[key]
        heading = _heading(title, status, sec, res if status == "error" else None)
        body = res.lines if status == "ok" else []
        if part == "summary":
            shown = (res.summary_lines or res.lines) if status == "ok" else []
            summary_parts += [heading] + shown + [""]
        else:
            full_parts += [heading] + body + [""]
    summary = "\n".join(summary_parts)
    report = summary + "\n" + "\n".join(full_parts) + "\n" + "\n".join(privacy.footer(ctx)) + (
        "\n<!-- Generated by the panel. Review before sharing. -->\n")

    summary = privacy.scrub(ctx, summary)
    report = privacy.scrub(ctx, report)
    try:
        sha = so.panel_integrity().get("current_sha") or "unknown"
    except Exception:  # noqa: BLE001
        sha = "unknown"
    return {"report": report, "summary": summary, "issue_body": _size_issue_body(summary),
            "issues_url": so._github_issues_url(),
            "filename": "linuxgsm-panel-debug-%s-%s.md" % (sha, time.strftime("%Y%m%d-%H%M%S"))}
